'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Code2,Play,Pause,RotateCcw,Maximize,Volume2,Check,Film} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
const titles=['First light','The village','Timber run','Stone and steel','The northern road','A place to return','The watch','Supplies','The warning','Last light','Close the doors','The first rain','They are here','The eastern line','Thunder','No way back','The breach','One last stand','First light returns','The second morning'];
const clock=(s:number)=>[Math.floor(s/3600),Math.floor(s/60)%60,Math.floor(s)%60].map(n=>String(n).padStart(2,'0')).join(':');
export default function Home(){
 const frame=useRef<HTMLIFrameElement>(null),screen=useRef<HTMLElement>(null);const [current,setCurrent]=useState(0),[playing,setPlaying]=useState(false),[ready,setReady]=useState(false),[volume,setVolume]=useState(.65),[failed,setFailed]=useState(false);
 const send=(type:string,extra:Record<string,number>={})=>frame.current?.contentWindow?.postMessage({type,...extra},window.location.origin);
 useEffect(()=>{const listener=(e:MessageEvent)=>{if(e.origin!==window.location.origin||e.source!==frame.current?.contentWindow)return;if(e.data.type==='movie-ready'){setReady(true);setFailed(false);}if(e.data.type==='movie-state'){setCurrent(e.data.time);setPlaying(e.data.playing);setReady(true);}if(e.data.type==='movie-error')setFailed(true);};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener)},[]);
 function seek(t:number){setCurrent(t);send('movie-seek',{time:t});}
 function play(){if(current>=18000)seek(0);send(playing?'movie-pause':'movie-play');}
 return <main><header><a className="brand" href="./"><span className="brand-icon"><Film size={20}/></span>MINE BUILD DEFEAT <span className="edition">/ SURVIVAL CINEMA</span></a><a className="game-link" href="https://riodebajyoti.github.io/mine_build_defeat/" target="_blank" rel="noreferrer">Play the game <ArrowUpRight size={17}/></a></header>
 <div className="heading"><div><p className="eyebrow"><span/> A MORNING. A NIGHT. A NEW DAY.</p><h1>Survive the night<span>.</span></h1></div><div className="film-meta"><span>5 HOURS</span><span>20 CHAPTERS</span><span>WITH SOUND</span></div></div>
 <section className="screen" ref={screen} aria-label="Five-hour movie player"><div className="movie-stage"><iframe ref={frame} src="./film/movie.html" title="Survive the Night — first-person movie" allow="autoplay; fullscreen" loading="eager" onLoad={()=>send('movie-sync')} onError={()=>setFailed(true)}/>{!ready&&!failed&&<div className="movie-loading">Preparing the village…</div>}{failed&&<div className="movie-loading">The movie could not start.<button onClick={()=>{setFailed(false);setReady(false);if(frame.current)frame.current.src='./film/movie.html?retry='+Date.now()}}>Try again</button></div>}{ready&&!playing&&<button className="play-cover" onClick={play}><Play size={23} fill="currentColor"/>{current>=18000?'WATCH AGAIN':current>0?'CONTINUE THE MOVIE':'BEGIN THE MOVIE'}</button>}</div>
 <div className="movie-controls"><div className="timeline-row"><Slider aria-label="Movie timeline" min={0} max={18000} step={1} value={[current]} onValueChange={v=>seek(Array.isArray(v)?v[0]:v)} disabled={!ready}/></div><div className="control-row"><button onClick={play} disabled={!ready} aria-label={playing?'Pause movie':'Play movie'}>{playing?<Pause size={21}/>:<Play size={21}/>}</button><button onClick={()=>seek(0)} disabled={!ready} aria-label="Restart movie"><RotateCcw size={17}/></button><span className="timecode">{clock(current)} <span>/ 05:00:00</span></span><div className="volume-control"><Volume2 size={17}/><Slider aria-label="Sound volume" min={0} max={1} step={.01} value={[volume]} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;setVolume(n);send('movie-volume',{volume:n})}}/></div><button aria-label="Enter fullscreen" onClick={()=>screen.current?.requestFullscreen().catch(()=>{})}><Maximize size={19}/></button></div></div></section>
 <div className="below"><div className="synopsis"><span className="status"><Check size={15}/> MISSION: REACH THE SECOND MORNING</span><p>Meet the villagers. Prepare the village. Hold the line through the storm.<br/>The story ends at the second morning, exactly five hours into playback.</p><p className="disclosure">A scripted movie animated live from the original game’s world and models. Includes smooth first-person movement, villagers, guardians, zombies, music, and sound effects. Pause or jump to any chapter.</p></div><div className="downloads"><a className="download-primary" href="./film-source.zip" download><Code2 size={18}/> Download movie code</a><span className="local-note">Plays in your browser · No account required</span></div></div>
 <section className="chapters"><div className="section-label"><h2>The whole story</h2><span>20 CHAPTERS · 15 MINUTES EACH</span></div><div className="chapter-grid">{titles.map((title,i)=><button key={title} disabled={!ready} className={Math.min(19,Math.floor(current/900))===i?'chapter active':'chapter'} onClick={()=>{seek(i*900);send('movie-play')}}><span className="chapter-number">{String(i+1).padStart(2,'0')}<span>{clock(i*900)}</span></span><strong>{title}</strong><small>{i<9?'Day one':i<12?'Sunset':i<18?'The long night':'Day two'}</small></button>)}</div></section>
 <footer><span>Original game by riodebajyoti · A movie made with code.</span><span><Volume2 size={14}/> Music, weather, footsteps, and combat audio</span></footer></main>;
}
